name: loan_app
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.15
  intl_phone_field: ^3.1.0
  curved_navigation_bar: ^1.0.3
  get: ^4.6.5
  animated_bottom_navigation_bar: ^1.1.0
  flutter_svg: ^1.1.5
  flutter_screenutil: ^5.5.4
  hexcolor: ^3.0.1
  get_storage: ^2.0.3
  dio: ^4.0.6
  flutter_otp_text_field: ^1.1.1
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  flutter_speed_dial: ^6.2.0
  fab_circular_menu: ^1.0.2
  circular_menu: ^2.0.1
  flutter_expandable_fab: ^1.6.0
  floating_bottom_bar: ^0.0.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  mockito: ^5.3.2
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true


  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
