const  Map<String, String> ar ={
"onBoardingTitle1": "احصل على قروض سريعة",
  "description1":'احصل بسهولة على القروض باستخدام هاتفك',

"onBoardingTitle2": "سهل ومريح",
"description2": "لا ضامنين ، لا قوائم انتظار طويلة ، بلا أوراق.",
"onBoardingTitle3": "تابع كل شيء",
"description3":'''رحلتك المالية تبدأ هنا''',
'button1':'ابدأ',
  'skip':'تجاهل',
  'signin':'تسجيل الدخول',
  'setup':'قم باعداد حسابك',

  'enterphhone':'أدخل رقم الهاتف',
  'button2':'متابعة',
  'hint1':'أدخل رقم الهاتف',
  "screentitle1": "رمز التحقق",
  "verification": "لقد أرسلنا رمز OTP للتحقق من رقمك" ,
  "verificationhint": "لم يتم استلام الرمز؟",
  "resend": "إعادة الإرسال" ,
  "label1": "الاسم الكامل",
  "label2": "بريد إلكتروني",
  "label3": "تاريخ الميلاد",
  "label4": "العنوان",
  "label5": "رقم الهاتف",
  "label6": "الموعد النهائي",
  'label7': 'المبلغ',
  "hint01": "الاسم الأول",
  "hint02": "اسم العائلة",
  "hint03": "أدخل عنوان بريدك الإلكتروني",
  'hint04': 'dd / mm / yyyy',
  "hint05": "غزة" ,
  'location':'الموقع',
  'name':'الاسم',

  'odb':'ODB',

  "button3": "حفظ التغييرات",
  "homewelcome": "أهلا وسهلا بك ، جون" ,
  'view': 'عرض الكل',
  "username": "جون",
  "screentitle2": "قرض",
  "transaction": "معاملة",
  "button4": "سداد القرض",
  'button5':'تأكيد',

  "screentitle3": "المستخدمون" ,
  "hint30": "بحث",
  'screentitle4': 'ملفي الشخصي',
  "screentitle5": "الإشعارات",
  'screentitle6':'اطلب',

  'presonaldetails': 'التفاصيل الشخصية',
  "deb&cred": "المدينون والدائنون" ,
  "setting": "الإعدادات" ,
  "logout": "تسجيل الخروج",
  "theme": "الثيم",
  "language": "اللغة",
  'button7':' ارسال رسالة',
  'english':'الانجليزية',
  'arabic':'العربية',
  'system':'وضع الجهاز',
  'light':'مضيء',
  'dark':'معتم',
  'accept':'قبول',
  'reject':'رفض'

};